# WebDAV, CalDAV, and CardDAV client for nodejs and the browser. - https://github.com/lambdabaa/dav
#
# Author: Georgy Berdyshev
#

language: node_js
sudo: required
env:
  - php_version: 7.3
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
before_install:
  - sudo add-apt-repository "deb [arch=amd64] http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -cs) main"
  - sudo apt-get update
  - 'sudo apt-get -y --allow-unauthenticated install php${php_version}-cli php${php_version}-sqlite3 php${php_version}-xml php${php_version}-mbstring'
install: npm install
script: npm test
